sftp:
  config:
    remoteDirectory: /upload/in/statements/
    localDirectory: tmp/
    host: localhost
    user: tester
    password: password
    port: 22

spring:
  kafka:
    producer:
      client-id: ecs-bank-statement-producer
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081

s3:
  config:
    url: http://localhost:4566
    region: eu-west-1
    access-key-id: test
    secret-key-id: test

application:
  config:
    reader:
      integration-code: ecs-bank
      process: STATEMENTS
      validation-required: true
      topic: statement.fct.files.0
