server:
  port: 9090
spring:
  kafka:
    streams:
      application-id: statement-audit-view
      replication-factor: 1
    properties:
      basic:
        auth:
          credentials:
            source:
          user:
            info:
      schema:
        registry:
          url: http://localhost:8081
  cloud:
    stream:
      function:
        definition: statementAuditViewMaterialized;statementHistoryAuditViewMaterialized
      bindings:
        statementAuditViewMaterialized-in-0:
            destination: statement.fct.ecs.files
        statementAuditViewMaterialized-out-0:
            destination: statement.view.ecs.files
        statementHistoryAuditViewMaterialized-in-0:
            destination: statement.fct.ecs.files
      kafka:
        streams:
          binder:
            brokers: http://localhost:9092
            deserializationExceptionHandler: sendToDlq
            configuration:
              schema.registry.url: http://localhost:8081
              commit.interval.ms: 80000
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            functions:
              streamStatementFileProcessor:
                applicationId: streamStatementFileProcessor
              statementAuditViewMaterialized:
                applicationId: statementAuditViewMaterialized
          bingings:
            statementAuditViewMaterialized-in-0:
              consumer:
                dlqName: statement.view.ecs.files.dlq
          

